/*
 * This source file was generated by the Gradle 'init' task
 */
package de.functionPlotter.App;

class MessageUtils {
    public static String getMessage() {
        return "Hello World!";
    }
}
